### ISSUE TITLE
The bot should not post URIs

### ISSUE THREAD

**Issue by Aldarone** [Srol/mastodon-ebooks#2]
In the first toot my bot made there is a media url, I think this is generally unwanted so you might wanna filter out URI schemes.

https://ltch.fr/@adlA/99341534540094826

**Comment by Srol** [comment]
Will be addressed in update today.

**Comment by Srol** [comment]
Should be fixed by latest update. It does require you to regenerate the corpus if you have a version of the bot already running. I included a script to do that and instructions in the readme.
