### ISSUE TITLE
The bot shouldn't post mentions

### ISSUE THREAD

**Issue by Aldarone** [Srol/mastodon-ebooks#3]
On second toot my bot tried to mention someone, I'm guessing this should be filtered out too 😉 

https://ltch.fr/@adlA/99341573845886548

**Comment by Srol** [comment]
Will be addressed in update today.

**Comment by Srol** [comment]
Should be fixed by latest update. It does require you to regenerate the corpus if you have a version of the bot already running. I included a script to do that and instructions in the readme.
